#define yy_create_buffer prehtml_create_buffer
#define yy_delete_buffer prehtml_delete_buffer
#define yy_scan_buffer prehtml_scan_buffer
#define yy_scan_string prehtml_scan_string
#define yy_scan_bytes prehtml_scan_bytes
#define yy_flex_debug prehtml_flex_debug
#define yy_init_buffer prehtml_init_buffer
#define yy_flush_buffer prehtml_flush_buffer
#define yy_load_buffer_state prehtml_load_buffer_state
#define yy_switch_to_buffer prehtml_switch_to_buffer
#define yyin prehtmlin
#define yyleng prehtmlleng
#define yylex prehtmllex
#define yyout prehtmlout
#define yyrestart prehtmlrestart
#define yytext prehtmltext
#define yywrap prehtmlwrap

#line 20 "prehtml.lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
static yyconst short int yy_accept[344] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       53,   53,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   76,   74,   46,   39,   52,   74,
       65,   65,   61,   65,   65,   75,   41,   41,   41,   53,
       54,   50,   51,   58,   58,   58,   70,   70,   69,   70,
       75,    0,    0,    0,    0,    0,    0,   55,   40,    0,
        0,    0,    0,    0,    0,   49,    0,    0,   56,   65,
       65,   65,   41,   42,   53,   58,    0,   70,   70,    0,
        0,    0,    3,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   67,   60,    0,    0,    0,    0,

       65,   65,   53,    0,    0,    0,   70,   44,   38,    0,
        0,    0,    0,    0,    0,    0,    0,   43,    0,    0,
        0,    0,   48,   49,    0,    0,    0,    0,    0,    0,
       66,   65,   65,   53,    0,    0,    0,    0,   70,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   71,   72,    0,   73,   57,
       45,    0,    0,   65,    0,   53,    0,    0,    0,    0,
       70,    4,    5,    6,    7,    8,    9,   10,   11,   12,

       13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   35,   36,   37,    2,    1,   47,    0,    0,
        0,   62,   63,   53,    0,    0,    0,    0,    0,   64,
       62,   63,   53,   59,    0,    0,   68,   64,   53,   68,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    1,    6,    1,    1,
        1,    1,    1,    1,    7,    1,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,    1,   19,   20,
       21,   22,   23,    1,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   30,   30,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   30,   30,   44,   30,
        1,    1,    1,    1,    1,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   30,   30,   33,   34,   35,
       36,   37,   38,   39,   40,   41,   42,   43,   30,   30,
       44,   30,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[45] =
    {   0,
        1,    1,    1,    2,    3,    1,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    1,
        1,    5,    1,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6
    } ;

static yyconst short int yy_base[461] =
    {   0,
        0,    1,   23,   64,    0,    0,    0,    0,  105,  128,
      274,  273,    0,    0,    0,    0,  272,  271,  151,  174,
      197,  240,  285,  284,  290, 1073, 1073,    0,  281,  266,
     1073,    0, 1073,  246,  242, 1073, 1073,    0,  263,    0,
     1073, 1073, 1073, 1073,    0,  274, 1073,    0, 1073,  257,
      273,  269,   13,   14,   31,  271,   15, 1073, 1073,  238,
      244,  239,  246,  241,  239,  232,    8,  237, 1073,    0,
      245,  231,    0, 1073,    0,    0,   48,    0,  234,  244,
      246,  315, 1073,   35,   42,  257,  226,  224,  217,  222,
      232,  210,  213,  227, 1073, 1073,  222,  210,  195,  216,

      198,  208,    0,  199,  206,   15,  191, 1073, 1073,   41,
      326,  337,  348,   43,   73,   77,   75, 1073,  210,  209,
      202,  207, 1073, 1073,  194,  200,  204,  193,  191,  201,
     1073,  181,  200,    0,  176,  190,  174,  168,  183,  191,
      190,  189,  188,  187,  173,  172,  171,  170,  169,  168,
      167,  166,  165,  164,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  127,  126,  125,  124,  123,  122,
      121,  120,  119,   71,   76, 1073, 1073,  115, 1073, 1073,
     1073,   86,   94,  100,  364,    0,   86,   92,   86,   84,
       94, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073,

     1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073,
     1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073,
     1073, 1073, 1073, 1073, 1073, 1073, 1073, 1073,   62,   98,
      379,   97,   96,    0,   77,   61,   69,   89,   87,   70,
     1073, 1073,    0, 1073,   14,    5,    4, 1073,    0, 1073,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0, 1073, 1073,  397,  403,  409,  415,  421,  427,  433,
      439,  443,  446,  449,  455,  458,  461,    0,  467,  473,
      479,  485,  490,  496,  501,  505,  510,  514,  520,  526,
      532,  538,  544,  550,  556,  562,  568,  574,  580,  586,
      592,  598,  604,  610,  616,  622,  628,  634,  640,  646,
      652,  658,  664,  670,  676,  682,  688,  694,  700,  706,

      712,  718,  724,  730,  736,  742,  748,  754,  760,  766,
      772,  778,  784,  790,  796,  802,  808,  814,  820,  826,
      832,  838,  844,  850,  856,  862,  868,  874,  880,  886,
      892,  898,  904,  910,  916,  922,  928,  934,  940,  946,
      952,  958,  964,  970,  976,  982,  988,  994, 1000, 1006,
     1012, 1018, 1024, 1030, 1036, 1042, 1048, 1054, 1060, 1066
    } ;

static yyconst short int yy_def[461] =
    {   0,
      344,  344,  345,  345,  346,  346,  346,  346,  347,  347,
      348,  348,  346,  346,  346,  346,  349,  349,  350,  350,
      351,  351,  346,  346,  343,  343,  343,  352,  343,  343,
      343,  353,  343,  353,  353,  343,  343,  354,  343,  355,
      343,  343,  343,  343,  356,  343,  343,  357,  343,  357,
      343,  358,  352,  352,  352,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  353,
      353,  353,  354,  343,  359,  356,  343,  357,  357,  343,
      358,  343,  343,  352,  352,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  360,

      353,  353,  361,  343,  343,  343,  357,  343,  343,  358,
      343,  343,  343,  358,  358,  352,  352,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  360,
      343,  353,  353,  362,  343,  343,  343,  343,  357,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  352,  352,  343,  343,  343,  343,  343,
      343,  343,  343,  353,  363,  364,  343,  343,  343,  343,
      357,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  365,
      363,  343,  343,  366,  343,  343,  343,  367,  365,  365,
      343,  343,  368,  343,  343,  367,  367,  343,  369,  343,
      370,  371,  372,  373,  374,  375,  376,  377,  378,  379,
      380,  381,  382,  383,  384,  385,  386,  387,  388,  389,
      390,  391,  392,  393,  394,  395,  396,  397,  398,  399,
      400,  401,  402,  403,  404,  405,  406,  407,  408,  409,
      410,  411,  412,  413,  414,  415,  416,  417,  418,  419,

      420,  421,  422,  423,  424,  425,  426,  427,  428,  429,
      430,  431,  432,  433,  434,  435,  436,  437,  438,  439,
      440,  441,  442,  443,  444,  445,  446,  447,  448,  449,
      450,  451,  452,  453,  454,  455,  456,  457,  458,  459,
      460,  343,    0,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343
    } ;

static yyconst short int yy_nxt[1118] =
    {   0,
      343,   27,   27,   81,   52,   28,   28,  250,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,   29,
       29,   30,   30,   31,   31,   31,   31,   31,   31,   31,
       31,   83,   83,   98,   54,  343,  343,   55,   84,  343,
      137,   31,   31,   31,   33,   31,  343,   87,   99,   83,
       88,   89,  172,   83,  235,  138,   90,  140,  141,  109,
       83,  109,   34,   35,   31,   31,   31,   31,   31,   31,
       31,   31,   85,  248,  116,  343,  104,  117,  105,  343,
      343,  343,   31,   31,   31,   33,   31,  106,  173,  226,
      343,  109,  246,   83,  227,   83,  235,  245,  244,  242,

      241,  239,  180,   34,   35,   37,   37,   37,   37,   37,
       37,   37,   37,  174,  238,  175,  237,  236,  235,  235,
      230,  180,  229,   37,   37,   37,   37,   39,   37,   37,
       37,   37,   37,   37,   37,   37,  228,  225,  224,  223,
      222,  221,  220,  219,  218,  217,   37,   37,   37,   37,
       39,   44,   44,   44,   44,   44,   44,   44,   44,  216,
      215,  214,  213,  212,  211,  210,  209,  208,  207,   44,
       46,   44,   44,   44,   44,   44,   44,   44,   44,   44,
       44,   44,  206,  205,  204,  203,  202,  201,  200,  199,
      198,  197,   44,   46,   44,   44,   44,   47,   47,   47,

       47,   47,   47,   47,   47,  196,  195,  194,  193,  192,
      191,  190,  189,  188,  187,   47,   47,   47,   49,   47,
      185,  184,  131,  183,  182,  181,  180,  180,  179,  178,
      177,  176,  139,  136,  135,  133,  132,  131,  129,   50,
       47,   47,   47,   47,   47,   47,   47,   47,  128,  127,
      126,  125,  124,  123,  122,  121,  120,  119,   47,   47,
       47,   49,   47,  118,  109,  108,  107,  102,  101,  100,
       97,   96,   95,   94,   93,   92,   91,   86,   82,   80,
       79,   77,   50,   56,   74,   72,   71,   69,   57,  343,
       51,   51,   43,   43,   41,   41,  343,  343,  343,  343,

       58,  343,  343,   59,  343,   60,  343,   61,  343,   62,
      343,   63,  343,   64,  343,  343,   65,   66,  343,  343,
       67,  343,   68,   81,   81,  110,  111,  112,  113,   81,
      114,  115,   81,  109,  142,  143,  144,  145,  146,  147,
      148,  149,  150,  151,  109,  152,  153,  154,  155,  156,
      157,  158,  159,  160,  161,  109,  162,  163,  164,  165,
      166,  167,  168,  169,  170,  171,  109,  231,  343,  343,
      343,  343,  232,  232,  232,  232,  232,  232,  232,  232,
      232,  232,  343,  343,  343,  343,  343,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  232,   26,   26,   26,

       26,   26,   26,   32,   32,   32,   32,   32,   32,   36,
       36,   36,   36,   36,   36,   38,   38,   38,   38,   38,
       38,   40,   40,   40,   40,   40,   40,   42,   42,   42,
       42,   42,   42,   45,   45,   45,   45,   45,   45,   48,
       48,   48,   48,   48,   48,   53,  343,  343,   53,   70,
      343,   70,   73,  343,   73,   75,   75,   75,   75,  343,
       75,   76,  343,   76,   78,  343,   78,  103,  103,  103,
      103,  343,  103,  130,  130,  130,  130,  130,  130,  134,
      134,  134,  134,  343,  134,  186,  186,  186,  186,  343,
      186,  233,  343,  233,  343,  233,  234,  234,  234,  234,

      343,  234,  240,  343,  240,  243,  243,  243,  243,  343,
      243,  247,  343,  247,  249,  249,  249,  249,  343,  249,
      251,  251,  251,  251,  343,  251,  252,  252,  252,  252,
      343,  252,  253,  253,  253,  253,  343,  253,  254,  254,
      254,  254,  343,  254,  255,  255,  255,  255,  343,  255,
      256,  256,  256,  256,  343,  256,  257,  257,  257,  257,
      343,  257,  258,  258,  258,  258,  343,  258,  259,  259,
      259,  259,  343,  259,  260,  260,  260,  260,  343,  260,
      261,  261,  261,  261,  343,  261,  262,  262,  262,  262,
      343,  262,  263,  263,  263,  263,  343,  263,  264,  264,

      264,  264,  343,  264,  265,  265,  265,  265,  343,  265,
      266,  266,  266,  266,  343,  266,  267,  267,  267,  267,
      343,  267,  268,  268,  268,  268,  343,  268,  269,  269,
      269,  269,  343,  269,  270,  270,  270,  270,  343,  270,
      271,  271,  271,  271,  343,  271,  272,  272,  272,  272,
      343,  272,  273,  273,  273,  273,  343,  273,  274,  274,
      274,  274,  343,  274,  275,  275,  275,  275,  343,  275,
      276,  276,  276,  276,  343,  276,  277,  277,  277,  277,
      343,  277,  278,  278,  278,  278,  343,  278,  279,  279,
      279,  279,  343,  279,  280,  280,  280,  280,  343,  280,

      281,  281,  281,  281,  343,  281,  282,  282,  282,  282,
      343,  282,  283,  283,  283,  283,  343,  283,  284,  284,
      284,  284,  343,  284,  285,  285,  285,  285,  343,  285,
      286,  286,  286,  286,  343,  286,  287,  287,  287,  287,
      343,  287,  288,  288,  288,  288,  343,  288,  289,  289,
      289,  289,  343,  289,  290,  290,  290,  290,  343,  290,
      291,  291,  291,  291,  343,  291,  292,  292,  292,  292,
      343,  292,  293,  293,  293,  293,  343,  293,  294,  294,
      294,  294,  343,  294,  295,  295,  295,  295,  343,  295,
      296,  296,  296,  296,  343,  296,  297,  297,  297,  297,

      343,  297,  298,  298,  298,  298,  343,  298,  299,  299,
      299,  299,  343,  299,  300,  300,  300,  300,  343,  300,
      301,  301,  301,  301,  343,  301,  302,  302,  302,  302,
      343,  302,  303,  303,  303,  303,  343,  303,  304,  304,
      304,  304,  343,  304,  305,  305,  305,  305,  343,  305,
      306,  306,  306,  306,  343,  306,  307,  307,  307,  307,
      343,  307,  308,  308,  308,  308,  343,  308,  309,  309,
      309,  309,  343,  309,  310,  310,  310,  310,  343,  310,
      311,  311,  311,  311,  343,  311,  312,  312,  312,  312,
      343,  312,  313,  313,  313,  313,  343,  313,  314,  314,

      314,  314,  343,  314,  315,  315,  315,  315,  343,  315,
      316,  316,  316,  316,  343,  316,  317,  317,  317,  317,
      343,  317,  318,  318,  318,  318,  343,  318,  319,  319,
      319,  319,  343,  319,  320,  320,  320,  320,  343,  320,
      321,  321,  321,  321,  343,  321,  322,  322,  322,  322,
      343,  322,  323,  323,  323,  323,  343,  323,  324,  324,
      324,  324,  343,  324,  325,  325,  325,  325,  343,  325,
      326,  326,  326,  326,  343,  326,  327,  327,  327,  327,
      343,  327,  328,  328,  328,  328,  343,  328,  329,  329,
      329,  329,  343,  329,  330,  330,  330,  330,  343,  330,

      331,  331,  331,  331,  343,  331,  332,  332,  332,  332,
      343,  332,  333,  333,  333,  333,  343,  333,  334,  334,
      334,  334,  343,  334,  335,  335,  335,  335,  343,  335,
      336,  336,  336,  336,  343,  336,  337,  337,  337,  337,
      343,  337,  338,  338,  338,  338,  343,  338,  339,  339,
      339,  339,  343,  339,  340,  340,  340,  340,  343,  340,
      341,  341,  341,  341,  343,  341,  342,  342,  342,  342,
      343,  342,   25,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yyconst short int yy_chk[1118] =
    {   0,
        0,    1,    2,  358,   28,    1,    2,  247,  246,    0,
        0,    0,    0,    0,    0,    0,    0,   53,   54,    1,
        2,    1,    2,    3,    3,    3,    3,    3,    3,    3,
        3,   53,   54,   67,   28,   55,    0,   28,   54,   84,
      106,    3,    3,    3,    3,    3,   85,   57,   67,   55,
       57,   57,  114,   84,  245,  106,   57,  110,  110,  110,
       85,  114,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    4,   55,  240,   84,  174,   77,   85,   77,  117,
      175,  116,    4,    4,    4,    4,    4,   77,  115,  174,
      239,  115,  238,  117,  175,  116,  237,  236,  235,  233,

      232,  230,  229,    4,    4,    9,    9,    9,    9,    9,
        9,    9,    9,  116,  191,  117,  190,  189,  188,  187,
      184,  183,  182,    9,    9,    9,    9,    9,   10,   10,
       10,   10,   10,   10,   10,   10,  178,  173,  172,  171,
      170,  169,  168,  167,  166,  165,   10,   10,   10,   10,
       10,   19,   19,   19,   19,   19,   19,   19,   19,  164,
      163,  162,  161,  160,  159,  158,  157,  156,  155,   19,
       19,   19,   19,   19,   20,   20,   20,   20,   20,   20,
       20,   20,  154,  153,  152,  151,  150,  149,  148,  147,
      146,  145,   20,   20,   20,   20,   20,   21,   21,   21,

       21,   21,   21,   21,   21,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,   21,   21,   21,   21,   21,
      133,  132,  130,  129,  128,  127,  126,  125,  122,  121,
      120,  119,  107,  105,  104,  102,  101,  100,   99,   21,
       22,   22,   22,   22,   22,   22,   22,   22,   98,   97,
       94,   93,   92,   91,   90,   89,   88,   87,   22,   22,
       22,   22,   22,   86,   81,   80,   79,   72,   71,   68,
       66,   65,   64,   63,   62,   61,   60,   56,   52,   51,
       50,   46,   22,   29,   39,   35,   34,   30,   29,   25,
       24,   23,   18,   17,   12,   11,    0,    0,    0,    0,

       29,    0,    0,   29,    0,   29,    0,   29,    0,   29,
        0,   29,    0,   29,    0,    0,   29,   29,    0,    0,
       29,    0,   29,   82,   82,   82,   82,   82,   82,   82,
       82,   82,   82,   82,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  113,  113,  113,  113,
      113,  113,  113,  113,  113,  113,  113,  185,    0,    0,
        0,    0,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  231,    0,    0,    0,    0,  231,  231,  231,
      231,  231,  231,  231,  231,  231,  231,  344,  344,  344,

      344,  344,  344,  345,  345,  345,  345,  345,  345,  346,
      346,  346,  346,  346,  346,  347,  347,  347,  347,  347,
      347,  348,  348,  348,  348,  348,  348,  349,  349,  349,
      349,  349,  349,  350,  350,  350,  350,  350,  350,  351,
      351,  351,  351,  351,  351,  352,    0,    0,  352,  353,
        0,  353,  354,    0,  354,  355,  355,  355,  355,    0,
      355,  356,    0,  356,  357,    0,  357,  359,  359,  359,
      359,    0,  359,  360,  360,  360,  360,  360,  360,  361,
      361,  361,  361,    0,  361,  362,  362,  362,  362,    0,
      362,  363,    0,  363,    0,  363,  364,  364,  364,  364,

        0,  364,  365,    0,  365,  366,  366,  366,  366,    0,
      366,  367,    0,  367,  368,  368,  368,  368,    0,  368,
      369,  369,  369,  369,    0,  369,  370,  370,  370,  370,
        0,  370,  371,  371,  371,  371,    0,  371,  372,  372,
      372,  372,    0,  372,  373,  373,  373,  373,    0,  373,
      374,  374,  374,  374,    0,  374,  375,  375,  375,  375,
        0,  375,  376,  376,  376,  376,    0,  376,  377,  377,
      377,  377,    0,  377,  378,  378,  378,  378,    0,  378,
      379,  379,  379,  379,    0,  379,  380,  380,  380,  380,
        0,  380,  381,  381,  381,  381,    0,  381,  382,  382,

      382,  382,    0,  382,  383,  383,  383,  383,    0,  383,
      384,  384,  384,  384,    0,  384,  385,  385,  385,  385,
        0,  385,  386,  386,  386,  386,    0,  386,  387,  387,
      387,  387,    0,  387,  388,  388,  388,  388,    0,  388,
      389,  389,  389,  389,    0,  389,  390,  390,  390,  390,
        0,  390,  391,  391,  391,  391,    0,  391,  392,  392,
      392,  392,    0,  392,  393,  393,  393,  393,    0,  393,
      394,  394,  394,  394,    0,  394,  395,  395,  395,  395,
        0,  395,  396,  396,  396,  396,    0,  396,  397,  397,
      397,  397,    0,  397,  398,  398,  398,  398,    0,  398,

      399,  399,  399,  399,    0,  399,  400,  400,  400,  400,
        0,  400,  401,  401,  401,  401,    0,  401,  402,  402,
      402,  402,    0,  402,  403,  403,  403,  403,    0,  403,
      404,  404,  404,  404,    0,  404,  405,  405,  405,  405,
        0,  405,  406,  406,  406,  406,    0,  406,  407,  407,
      407,  407,    0,  407,  408,  408,  408,  408,    0,  408,
      409,  409,  409,  409,    0,  409,  410,  410,  410,  410,
        0,  410,  411,  411,  411,  411,    0,  411,  412,  412,
      412,  412,    0,  412,  413,  413,  413,  413,    0,  413,
      414,  414,  414,  414,    0,  414,  415,  415,  415,  415,

        0,  415,  416,  416,  416,  416,    0,  416,  417,  417,
      417,  417,    0,  417,  418,  418,  418,  418,    0,  418,
      419,  419,  419,  419,    0,  419,  420,  420,  420,  420,
        0,  420,  421,  421,  421,  421,    0,  421,  422,  422,
      422,  422,    0,  422,  423,  423,  423,  423,    0,  423,
      424,  424,  424,  424,    0,  424,  425,  425,  425,  425,
        0,  425,  426,  426,  426,  426,    0,  426,  427,  427,
      427,  427,    0,  427,  428,  428,  428,  428,    0,  428,
      429,  429,  429,  429,    0,  429,  430,  430,  430,  430,
        0,  430,  431,  431,  431,  431,    0,  431,  432,  432,

      432,  432,    0,  432,  433,  433,  433,  433,    0,  433,
      434,  434,  434,  434,    0,  434,  435,  435,  435,  435,
        0,  435,  436,  436,  436,  436,    0,  436,  437,  437,
      437,  437,    0,  437,  438,  438,  438,  438,    0,  438,
      439,  439,  439,  439,    0,  439,  440,  440,  440,  440,
        0,  440,  441,  441,  441,  441,    0,  441,  442,  442,
      442,  442,    0,  442,  443,  443,  443,  443,    0,  443,
      444,  444,  444,  444,    0,  444,  445,  445,  445,  445,
        0,  445,  446,  446,  446,  446,    0,  446,  447,  447,
      447,  447,    0,  447,  448,  448,  448,  448,    0,  448,

      449,  449,  449,  449,    0,  449,  450,  450,  450,  450,
        0,  450,  451,  451,  451,  451,    0,  451,  452,  452,
      452,  452,    0,  452,  453,  453,  453,  453,    0,  453,
      454,  454,  454,  454,    0,  454,  455,  455,  455,  455,
        0,  455,  456,  456,  456,  456,    0,  456,  457,  457,
      457,  457,    0,  457,  458,  458,  458,  458,    0,  458,
      459,  459,  459,  459,    0,  459,  460,  460,  460,  460,
        0,  460,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,

      343,  343,  343,  343,  343,  343,  343,  343,  343,  343,
      343,  343,  343,  343,  343,  343,  343
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "prehtml.lex"
#define INITIAL 0
/******************************************************************************
* Project:	xmLeges
* Module:	Marker
* File:		prehtml.lex
* Copyright:	ITTIG/CNR - Firenze - Italy (http://www.ittig.cnr.it)
* Licence:	GNU/GPL (http://www.gnu.org/licenses/gpl.html)
* Authors:	Mirco Taddei (m.taddei@ittig.cnr.it)
* 			Lorenzo Bacci (bacci@ittig.cnr.it)
******************************************************************************/
/*
//OLD InComment:

\<!--						{
							BEGIN(InComment);
							}

<InComment>({TKN}+|{Q})		{
							prehtmlAppendString(strdup(prehtmltext));
							}

<InComment>-->				{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(0);
							}											
*/
#line 29 "prehtml.lex"
#include <stdio.h>
#include <string.h>
#include <IttigUtil.h>
#include <IttigLogger.h>

#include "config.h"
#include "prehtml.h"
#include "pre.h"

int Lista[20];
int Tipo[20];
int ii,jj;
int flagpre = 0;
static int numStart;
char ExtractChar;

//char *numLI;
char *cifre = NULL;
char *Uita = NULL;

int prehtmlwrap() 
{
	return 1;
}

void azzera(void)
{

	for (ii=0; ii<20; ii++)
	{
		Lista[ii] = 0;
		Tipo[ii] = -1;
	}
	ii = 0;
	jj = 0;
}


//\<pre>							flagpre=1;

//{NL}							{
//								if (flagpre==0) prehtmlAppendChars(1,' ');
//								if (flagpre==1)	prehtmlAppendChars(1,'\n');}
								
//\<\/pre>						flagpre=0;


#define InTagLista 1
#define ListaTipo 2
#define ListaStart 3
#define InPI 4
#define InTag 5
#define InTagListaNonOrd 6

#define InTagBA 7
#define InTagDiv 8
#define InTagDel 9
#define InTagElementList 10
#define InComment 11

#define YY_STACK_USED 1
#line 855 "prehtml.lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 100 "prehtml.lex"


#line 1020 "prehtml.lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 344 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1073 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 102 "prehtml.lex"
prehtmlAppendChars(1, '"');		// convertite virgolette
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 103 "prehtml.lex"
prehtmlAppendChars(1, ' ');		// convertito spazio non divisibile
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 105 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));	// lasciate entità simboliche
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "prehtml.lex"
prehtmlAppendChars(1, '\x80');		//mapping dei caratteri "windows"
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 108 "prehtml.lex"
prehtmlAppendChars(1, '\x81');
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 109 "prehtml.lex"
prehtmlAppendChars(1, '\x82');
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 110 "prehtml.lex"
prehtmlAppendChars(1, '\x83');
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 111 "prehtml.lex"
prehtmlAppendChars(1, '\x84');
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 112 "prehtml.lex"
prehtmlAppendChars(1, '\x85');
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 113 "prehtml.lex"
prehtmlAppendChars(1, '\x86');
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "prehtml.lex"
prehtmlAppendChars(1, '\x87');
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "prehtml.lex"
prehtmlAppendChars(1, '\x88');
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "prehtml.lex"
prehtmlAppendChars(1, '\x89');
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "prehtml.lex"
prehtmlAppendChars(1, '\x8A');
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "prehtml.lex"
prehtmlAppendChars(1, '\x8B');
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "prehtml.lex"
prehtmlAppendChars(1, '\x8C');
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "prehtml.lex"
prehtmlAppendChars(1, '\x8D');
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "prehtml.lex"
prehtmlAppendChars(1, '\x8E');
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "prehtml.lex"
prehtmlAppendChars(1, '\x8F');
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "prehtml.lex"
prehtmlAppendChars(1, '\x90');
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "prehtml.lex"
prehtmlAppendChars(1, '\x91');
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "prehtml.lex"
prehtmlAppendChars(1, '\x92');
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 126 "prehtml.lex"
prehtmlAppendChars(1, '\x93');
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 127 "prehtml.lex"
prehtmlAppendChars(1, '\x94');
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 128 "prehtml.lex"
prehtmlAppendChars(1, '\x95');
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "prehtml.lex"
prehtmlAppendChars(1, '\x96');
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 130 "prehtml.lex"
prehtmlAppendChars(1, '\x97');
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 131 "prehtml.lex"
prehtmlAppendChars(1, '\x98');
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 132 "prehtml.lex"
prehtmlAppendChars(1, '\x99');
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 133 "prehtml.lex"
prehtmlAppendChars(1, '\x9A');
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 134 "prehtml.lex"
prehtmlAppendChars(1, '\x9B');
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 135 "prehtml.lex"
prehtmlAppendChars(1, '\x9C');
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 136 "prehtml.lex"
prehtmlAppendChars(1, '\x9D');
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 137 "prehtml.lex"
prehtmlAppendChars(1, '\x9E');
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 138 "prehtml.lex"
prehtmlAppendChars(1, '\x9F');
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 140 "prehtml.lex"
prehtmlAppendChars(1, '\xAB');		//#LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 141 "prehtml.lex"
prehtmlAppendChars(1, '\xBB');		//#RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 143 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));	// lasciate entità numeriche  //(..se ne rimangono..)
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "prehtml.lex"
prehtmlAppendString("&#38;");		// & che non delimita un'entità
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 149 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(InPI);}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 153 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 155 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(0);}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 159 "prehtml.lex"
{
							BEGIN(InComment);}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 162 "prehtml.lex"
{
							BEGIN(0);
							}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 166 "prehtml.lex"
{	
							flagpre=1;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 169 "prehtml.lex"
{
								if (flagpre==0) prehtmlAppendChars(1,' ');
								if (flagpre==1)	prehtmlAppendChars(1,'\n');}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 173 "prehtml.lex"
{
								flagpre=0;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 177 "prehtml.lex"
{
								prehtmlAppendChars(1, '\n'); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 180 "prehtml.lex"
{		
								prehtmlAppendChars(2, '\n');
								BEGIN(InTagDiv);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 183 "prehtml.lex"

	YY_BREAK
case 51:
YY_RULE_SETUP
#line 184 "prehtml.lex"
BEGIN(0);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 186 "prehtml.lex"
{
								BEGIN(InTag);}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 188 "prehtml.lex"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 189 "prehtml.lex"
{
								BEGIN(0);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 192 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 193 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 195 "prehtml.lex"
{
								jj++;							
								BEGIN(InTagDel);}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 198 "prehtml.lex"

	YY_BREAK
case 59:
YY_RULE_SETUP
#line 199 "prehtml.lex"
{
								jj--;
								if (jj==0)
									BEGIN(0);}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 204 "prehtml.lex"
{
								ii++;BEGIN(InTagLista);}	
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 206 "prehtml.lex"
{
								if (Tipo[ii]==-1) Tipo[ii]=1; //Se non c'è il tipo di defaut è numerica
								BEGIN(0);}					
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 210 "prehtml.lex"
{
								Tipo[ii]=1; //lista numerica
								}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 213 "prehtml.lex"
{
								Tipo[ii]=0; //lista alfabetica
								}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 216 "prehtml.lex"
{
								cifre=utilIsolaNum(yytext); 
								numStart = atoi(cifre);
								Lista[ii]=(numStart-1);
								}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 222 "prehtml.lex"

	YY_BREAK
case 66:
YY_RULE_SETUP
#line 224 "prehtml.lex"
ii++; Tipo[ii]=2; //lista puntata
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 230 "prehtml.lex"
Lista[ii]++;BEGIN(InTagElementList);
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 232 "prehtml.lex"
{
											cifre=utilIsolaNum(yytext); 
											numStart = atoi(cifre);
											Lista[ii]=(numStart-1);
											}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 238 "prehtml.lex"
{
						
						prehtmlAppendChars(2,'\n');
						if (Tipo[ii]==1)
							{
							
							Uita=utilItoa(Lista[ii]);					
							prehtmlAppendString(Uita);//visualizza il numero
							prehtmlAppendChars(1,')');
							prehtmlAppendChars(1,' ');
							}
						if (Tipo[ii]==0)
							{
							ExtractChar = prehtmlExtractChar(Lista[ii]);
							if (Lista[ii]<27)
								prehtmlAppendChars(1,ExtractChar);
							else if (Lista[ii]<677)
								prehtmlAppendChars(2,ExtractChar);
							else
								prehtmlAppendChars(3,ExtractChar);
							prehtmlAppendChars(1,')');
							prehtmlAppendChars(1,' ');
							}
						if (Tipo[ii]==2)
							{
							prehtmlAppendChars(1,'-');
							prehtmlAppendChars(1,' ');
							}

						BEGIN(0);
						}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 270 "prehtml.lex"

	YY_BREAK
case 71:
YY_RULE_SETUP
#line 277 "prehtml.lex"

	YY_BREAK
case 72:
YY_RULE_SETUP
#line 278 "prehtml.lex"
{
								prehtmlAppendChars(2,'\n');
								Lista[ii]=0;
								ii--; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 282 "prehtml.lex"
{
								prehtmlAppendChars(2,'\n');
								Lista[ii]=0;
								ii--; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 287 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 290 "prehtml.lex"
ECHO;
	YY_BREAK
#line 1550 "prehtml.lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(InTagLista):
case YY_STATE_EOF(ListaTipo):
case YY_STATE_EOF(ListaStart):
case YY_STATE_EOF(InPI):
case YY_STATE_EOF(InTag):
case YY_STATE_EOF(InTagListaNonOrd):
case YY_STATE_EOF(InTagBA):
case YY_STATE_EOF(InTagDiv):
case YY_STATE_EOF(InTagDel):
case YY_STATE_EOF(InTagElementList):
case YY_STATE_EOF(InComment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 344 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 344 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 343);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 290 "prehtml.lex"


/*
---------------------------------
cp 1252 Encoding (from cp1252.txt)
---------------------------------
=20	U+0020	SPACE
=21	U+0021	EXCLAMATION MARK
=22	U+0022	QUOTATION MARK
=23	U+0023	NUMBER SIGN
=24	U+0024	DOLLAR SIGN
=25	U+0025	PERCENT SIGN
=26	U+0026	AMPERSAND
=27	U+0027	APOSTROPHE
=28	U+0028	LEFT PARENTHESIS
=29	U+0029	RIGHT PARENTHESIS
=2A	U+002A	ASTERISK
=2B	U+002B	PLUS SIGN
=2C	U+002C	COMMA
=2D	U+002D	HYPHEN-MINUS
=2E	U+002E	FULL STOP
=2F	U+002F	SOLIDUS
=30	U+0030	DIGIT ZERO
=31	U+0031	DIGIT ONE
=32	U+0032	DIGIT TWO
=33	U+0033	DIGIT THREE
=34	U+0034	DIGIT FOUR
=35	U+0035	DIGIT FIVE
=36	U+0036	DIGIT SIX
=37	U+0037	DIGIT SEVEN
=38	U+0038	DIGIT EIGHT
=39	U+0039	DIGIT NINE
=3A	U+003A	COLON
=3B	U+003B	SEMICOLON
=3C	U+003C	LESS-THAN SIGN
=3D	U+003D	EQUALS SIGN
=3E	U+003E	GREATER-THAN SIGN
=3F	U+003F	QUESTION MARK
=40	U+0040	COMMERCIAL AT
=41	U+0041	LATIN CAPITAL LETTER A
=42	U+0042	LATIN CAPITAL LETTER B
=43	U+0043	LATIN CAPITAL LETTER C
=44	U+0044	LATIN CAPITAL LETTER D
=45	U+0045	LATIN CAPITAL LETTER E
=46	U+0046	LATIN CAPITAL LETTER F
=47	U+0047	LATIN CAPITAL LETTER G
=48	U+0048	LATIN CAPITAL LETTER H
=49	U+0049	LATIN CAPITAL LETTER I
=4A	U+004A	LATIN CAPITAL LETTER J
=4B	U+004B	LATIN CAPITAL LETTER K
=4C	U+004C	LATIN CAPITAL LETTER L
=4D	U+004D	LATIN CAPITAL LETTER M
=4E	U+004E	LATIN CAPITAL LETTER N
=4F	U+004F	LATIN CAPITAL LETTER O
=50	U+0050	LATIN CAPITAL LETTER P
=51	U+0051	LATIN CAPITAL LETTER Q
=52	U+0052	LATIN CAPITAL LETTER R
=53	U+0053	LATIN CAPITAL LETTER S
=54	U+0054	LATIN CAPITAL LETTER T
=55	U+0055	LATIN CAPITAL LETTER U
=56	U+0056	LATIN CAPITAL LETTER V
=57	U+0057	LATIN CAPITAL LETTER W
=58	U+0058	LATIN CAPITAL LETTER X
=59	U+0059	LATIN CAPITAL LETTER Y
=5A	U+005A	LATIN CAPITAL LETTER Z
=5B	U+005B	LEFT SQUARE BRACKET
=5C	U+005C	REVERSE SOLIDUS
=5D	U+005D	RIGHT SQUARE BRACKET
=5E	U+005E	CIRCUMFLEX ACCENT
=5F	U+005F	LOW LINE
=60	U+0060	GRAVE ACCENT
=61	U+0061	LATIN SMALL LETTER A
=62	U+0062	LATIN SMALL LETTER B
=63	U+0063	LATIN SMALL LETTER C
=64	U+0064	LATIN SMALL LETTER D
=65	U+0065	LATIN SMALL LETTER E
=66	U+0066	LATIN SMALL LETTER F
=67	U+0067	LATIN SMALL LETTER G
=68	U+0068	LATIN SMALL LETTER H
=69	U+0069	LATIN SMALL LETTER I
=6A	U+006A	LATIN SMALL LETTER J
=6B	U+006B	LATIN SMALL LETTER K
=6C	U+006C	LATIN SMALL LETTER L
=6D	U+006D	LATIN SMALL LETTER M
=6E	U+006E	LATIN SMALL LETTER N
=6F	U+006F	LATIN SMALL LETTER O
=70	U+0070	LATIN SMALL LETTER P
=71	U+0071	LATIN SMALL LETTER Q
=72	U+0072	LATIN SMALL LETTER R
=73	U+0073	LATIN SMALL LETTER S
=74	U+0074	LATIN SMALL LETTER T
=75	U+0075	LATIN SMALL LETTER U
=76	U+0076	LATIN SMALL LETTER V
=77	U+0077	LATIN SMALL LETTER W
=78	U+0078	LATIN SMALL LETTER X
=79	U+0079	LATIN SMALL LETTER Y
=7A	U+007A	LATIN SMALL LETTER Z
=7B	U+007B	LEFT CURLY BRACKET
=7C	U+007C	VERTICAL LINE
=7D	U+007D	RIGHT CURLY BRACKET
=7E	U+007E	TILDE
=80	U+20AC	EURO SIGN
=82	U+201A	SINGLE LOW-9 QUOTATION MARK
=83	U+0192	LATIN SMALL LETTER F WITH HOOK
=84	U+201E	DOUBLE LOW-9 QUOTATION MARK
=85	U+2026	HORIZONTAL ELLIPSIS
=86	U+2020	DAGGER
=87	U+2021	DOUBLE DAGGER
=88	U+02C6	MODIFIER LETTER CIRCUMFLEX ACCENT
=89	U+2030	PER MILLE SIGN
=8A	U+0160	LATIN CAPITAL LETTER S WITH CARON
=8B	U+2039	SINGLE LEFT-POINTING ANGLE QUOTATION MARK
=8C	U+0152	LATIN CAPITAL LIGATURE OE
=8E	U+017D	LATIN CAPITAL LETTER Z WITH CARON
=91	U+2018	LEFT SINGLE QUOTATION MARK
=92	U+2019	RIGHT SINGLE QUOTATION MARK
=93	U+201C	LEFT DOUBLE QUOTATION MARK
=94	U+201D	RIGHT DOUBLE QUOTATION MARK
=95	U+2022	BULLET
=96	U+2013	EN DASH
=97	U+2014	EM DASH
=98	U+02DC	SMALL TILDE
=99	U+2122	TRADE MARK SIGN
=9A	U+0161	LATIN SMALL LETTER S WITH CARON
=9B	U+203A	SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
=9C	U+0153	LATIN SMALL LIGATURE OE
=9E	U+017E	LATIN SMALL LETTER Z WITH CARON
=9F	U+0178	LATIN CAPITAL LETTER Y WITH DIAERESIS
=A0	U+00A0	NO-BREAK SPACE
=A1	U+00A1	INVERTED EXCLAMATION MARK
=A2	U+00A2	CENT SIGN
=A3	U+00A3	POUND SIGN
=A4	U+00A4	CURRENCY SIGN
=A5	U+00A5	YEN SIGN
=A6	U+00A6	BROKEN BAR
=A7	U+00A7	SECTION SIGN
=A8	U+00A8	DIAERESIS
=A9	U+00A9	COPYRIGHT SIGN
=AA	U+00AA	FEMININE ORDINAL INDICATOR
=AB	U+00AB	LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
=AC	U+00AC	NOT SIGN
=AD	U+00AD	SOFT HYPHEN
=AE	U+00AE	REGISTERED SIGN
=AF	U+00AF	MACRON
=B0	U+00B0	DEGREE SIGN
=B1	U+00B1	PLUS-MINUS SIGN
=B2	U+00B2	SUPERSCRIPT TWO
=B3	U+00B3	SUPERSCRIPT THREE
=B4	U+00B4	ACUTE ACCENT
=B5	U+00B5	MICRO SIGN
=B6	U+00B6	PILCROW SIGN
=B7	U+00B7	MIDDLE DOT
=B8	U+00B8	CEDILLA
=B9	U+00B9	SUPERSCRIPT ONE
=BA	U+00BA	MASCULINE ORDINAL INDICATOR
=BB	U+00BB	RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
=BC	U+00BC	VULGAR FRACTION ONE QUARTER
=BD	U+00BD	VULGAR FRACTION ONE HALF
=BE	U+00BE	VULGAR FRACTION THREE QUARTERS
=BF	U+00BF	INVERTED QUESTION MARK
=C0	U+00C0	LATIN CAPITAL LETTER A WITH GRAVE
=C1	U+00C1	LATIN CAPITAL LETTER A WITH ACUTE
=C2	U+00C2	LATIN CAPITAL LETTER A WITH CIRCUMFLEX
=C3	U+00C3	LATIN CAPITAL LETTER A WITH TILDE
=C4	U+00C4	LATIN CAPITAL LETTER A WITH DIAERESIS
=C5	U+00C5	LATIN CAPITAL LETTER A WITH RING ABOVE
=C6	U+00C6	LATIN CAPITAL LETTER AE
=C7	U+00C7	LATIN CAPITAL LETTER C WITH CEDILLA
=C8	U+00C8	LATIN CAPITAL LETTER E WITH GRAVE
=C9	U+00C9	LATIN CAPITAL LETTER E WITH ACUTE
=CA	U+00CA	LATIN CAPITAL LETTER E WITH CIRCUMFLEX
=CB	U+00CB	LATIN CAPITAL LETTER E WITH DIAERESIS
=CC	U+00CC	LATIN CAPITAL LETTER I WITH GRAVE
=CD	U+00CD	LATIN CAPITAL LETTER I WITH ACUTE
=CE	U+00CE	LATIN CAPITAL LETTER I WITH CIRCUMFLEX
=CF	U+00CF	LATIN CAPITAL LETTER I WITH DIAERESIS
=D0	U+00D0	LATIN CAPITAL LETTER ETH
=D1	U+00D1	LATIN CAPITAL LETTER N WITH TILDE
=D2	U+00D2	LATIN CAPITAL LETTER O WITH GRAVE
=D3	U+00D3	LATIN CAPITAL LETTER O WITH ACUTE
=D4	U+00D4	LATIN CAPITAL LETTER O WITH CIRCUMFLEX
=D5	U+00D5	LATIN CAPITAL LETTER O WITH TILDE
=D6	U+00D6	LATIN CAPITAL LETTER O WITH DIAERESIS
=D7	U+00D7	MULTIPLICATION SIGN
=D8	U+00D8	LATIN CAPITAL LETTER O WITH STROKE
=D9	U+00D9	LATIN CAPITAL LETTER U WITH GRAVE
=DA	U+00DA	LATIN CAPITAL LETTER U WITH ACUTE
=DB	U+00DB	LATIN CAPITAL LETTER U WITH CIRCUMFLEX
=DC	U+00DC	LATIN CAPITAL LETTER U WITH DIAERESIS
=DD	U+00DD	LATIN CAPITAL LETTER Y WITH ACUTE
=DE	U+00DE	LATIN CAPITAL LETTER THORN
=DF	U+00DF	LATIN SMALL LETTER SHARP S
=E0	U+00E0	LATIN SMALL LETTER A WITH GRAVE
=E1	U+00E1	LATIN SMALL LETTER A WITH ACUTE
=E2	U+00E2	LATIN SMALL LETTER A WITH CIRCUMFLEX
=E3	U+00E3	LATIN SMALL LETTER A WITH TILDE
=E4	U+00E4	LATIN SMALL LETTER A WITH DIAERESIS
=E5	U+00E5	LATIN SMALL LETTER A WITH RING ABOVE
=E6	U+00E6	LATIN SMALL LETTER AE
=E7	U+00E7	LATIN SMALL LETTER C WITH CEDILLA
=E8	U+00E8	LATIN SMALL LETTER E WITH GRAVE
=E9	U+00E9	LATIN SMALL LETTER E WITH ACUTE
=EA	U+00EA	LATIN SMALL LETTER E WITH CIRCUMFLEX
=EB	U+00EB	LATIN SMALL LETTER E WITH DIAERESIS
=EC	U+00EC	LATIN SMALL LETTER I WITH GRAVE
=ED	U+00ED	LATIN SMALL LETTER I WITH ACUTE
=EE	U+00EE	LATIN SMALL LETTER I WITH CIRCUMFLEX
=EF	U+00EF	LATIN SMALL LETTER I WITH DIAERESIS
=F0	U+00F0	LATIN SMALL LETTER ETH
=F1	U+00F1	LATIN SMALL LETTER N WITH TILDE
=F2	U+00F2	LATIN SMALL LETTER O WITH GRAVE
=F3	U+00F3	LATIN SMALL LETTER O WITH ACUTE
=F4	U+00F4	LATIN SMALL LETTER O WITH CIRCUMFLEX
=F5	U+00F5	LATIN SMALL LETTER O WITH TILDE
=F6	U+00F6	LATIN SMALL LETTER O WITH DIAERESIS
=F7	U+00F7	DIVISION SIGN
=F8	U+00F8	LATIN SMALL LETTER O WITH STROKE
=F9	U+00F9	LATIN SMALL LETTER U WITH GRAVE
=FA	U+00FA	LATIN SMALL LETTER U WITH ACUTE
=FB	U+00FB	LATIN SMALL LETTER U WITH CIRCUMFLEX
=FC	U+00FC	LATIN SMALL LETTER U WITH DIAERESIS
=FD	U+00FD	LATIN SMALL LETTER Y WITH ACUTE
=FE	U+00FE	LATIN SMALL LETTER THORN
=FF	U+00FF	LATIN SMALL LETTER Y WITH DIAERESIS
*/