#line 2 "annessi.lex.yy.c"

#line 4 "annessi.lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE annrestart(annin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int annleng;

extern FILE *annin, *annout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up anntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up anntext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via annrestart()), so that the user can continue scanning by
	 * just pointing annin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when anntext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int annleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow annwrap()'s to do buffer switches
 * instead of setting up a fresh annin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void annrestart (FILE *input_file  );
void ann_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE ann_create_buffer (FILE *file,int size  );
void ann_delete_buffer (YY_BUFFER_STATE b  );
void ann_flush_buffer (YY_BUFFER_STATE b  );
void annpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void annpop_buffer_state (void );

static void annensure_buffer_stack (void );
static void ann_load_buffer_state (void );
static void ann_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER ann_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE ann_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE ann_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE ann_scan_bytes (yyconst char *bytes,int len  );

void *annalloc (yy_size_t  );
void *annrealloc (void *,yy_size_t  );
void annfree (void *  );

#define yy_new_buffer ann_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        annensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ann_create_buffer(annin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        annensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            ann_create_buffer(annin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *annin = (FILE *) 0, *annout = (FILE *) 0;

typedef int yy_state_type;

extern int annlineno;

int annlineno = 1;

extern char *anntext;
#define yytext_ptr anntext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up anntext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	annleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 8
#define YY_END_OF_BUFFER 9
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_acclist[179] =
    {   0,
        9,    7,    8,    6,    7,    8,    7,    8,    6,    7,
        8,    6,    7,    8,    6,    7,    8,    5,    7,    8,
        4,    7,    8,    7,    8,    6,    7,    8,16386,    6,
        7,    8,    6,    7,    8,    6,    7,    8,    6,    7,
        8,16386,    6,    7,    8,    6,    7,    8,    6,    7,
        8,    6,    7,    8,    6,    7,    8,    6,    7,    8,
        6,    7,    8,    7,    8,    6,    7,    8,    6,    7,
        8,    6,    7,    8,    6,    6,    6,    6,    6, 8194,
        6,16386,    3,    6,    6,    6, 8194,    3,    6,16386,
        6,    6,    6,    6,    6,    6,    6,    6,16386,    6,

        6,    6,    6,16386,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,16386,    6,
        6,    6,    6,    6,    6,    6,    6,16386,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    1,    6,    6,    6,    6,    6,    1,
        1,    6,    6,    6,16386,    6,16386,    6
    } ;

static yyconst flex_int16_t yy_accept[246] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    4,    7,
        9,   12,   15,   18,   21,   24,   26,   30,   33,   36,
       39,   43,   46,   49,   52,   55,   58,   61,   64,   66,
       69,   72,   75,   76,   76,   76,   76,   76,   76,   77,
       78,   78,   79,   79,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   81,   81,   81,   83,   84,   84,   84,
       85,   86,   87,   89,   89,   89,   91,   92,   93,   94,
       95,   96,   97,   98,  100,  100,  100,  100,  100,  100,
      100,  100,  100,  100,  100,  101,  101,  102,  102,  103,
      103,  104,  104,  104,  104,  104,  104,  104,  104,  105,

      106,  107,  108,  109,  110,  111,  112,  113,  114,  115,
      116,  117,  118,  120,  121,  122,  122,  122,  122,  122,
      122,  123,  123,  124,  124,  125,  125,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  127,  129,  130,  131,
      132,  133,  134,  135,  136,  137,  138,  139,  140,  141,
      141,  141,  141,  141,  141,  142,  142,  143,  143,  144,
      144,  145,  145,  145,  145,  145,  145,  145,  145,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  154,  155,
      155,  155,  155,  155,  155,  156,  156,  157,  157,  158,
      158,  159,  159,  159,  159,  159,  159,  159,  159,  159,

      160,  161,  162,  163,  163,  163,  163,  163,  163,  164,
      164,  166,  166,  167,  167,  167,  167,  167,  167,  168,
      169,  170,  170,  171,  171,  171,  172,  172,  173,  173,
      173,  173,  174,  176,  176,  176,  177,  177,  178,  178,
      178,  179,  179,  179,  179
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    1,    1,    1,    1,    1,    1,    1,
        4,    1,    1,    1,    5,    1,    1,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    4,    1,    1,
        1,    1,    1,    1,    7,    8,    9,   10,   11,   12,
       13,   12,   14,   12,   12,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   12,   26,   12,   27,
        1,    1,    1,    1,    1,    1,    7,    8,    9,   10,

       11,   12,   13,   12,   14,   12,   12,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   12,   26,
       12,   27,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[28] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2
    } ;

static yyconst flex_int16_t yy_base[247] =
    {   0,
        0,    5,   28,  467,   33,   58,  468,  470,    0,   60,
        8,   61,   10,  470,  470,   78,   12,   17,   70,  101,
      124,   51,   67,   68,   82,   83,   86,   97,  108,  148,
      113,  129,    0,  138,  131,   63,   19,  139,  114,   96,
      119,  115,  155,  144,  453,  442,  447,  455,  439,  451,
      450,  443,  470,   68,  117,  164,  470,  171,  173,  437,
      449,  439,  470,  175,  177,  179,  167,  433,  432,  440,
      150,  184,  432,  209,  184,  183,  199,  194,  197,  202,
      152,  212,  218,  220,  219,  168,  221,  225,  222,  228,
      234,  430,  433,  425,  426,  184,  220,  427,  245,  433,

      126,  432,  431,  437,  427,  217,  425,  423,  417,  416,
      415,  423,  409,  424,  423,  239,  240,  249,  250,  251,
      254,  255,  238,  256,  261,  262,  265,  419,  418,  408,
      413,  406,  414,  416,  415,  409,  259,  413,  412,  397,
      398,  409,  251,  402,  404,  403,  405,  406,  397,  269,
      272,  274,  275,  278,  276,  282,  283,  284,  285,  292,
      293,  402,  401,  400,  390,  395,  397,  398,  389,  383,
      382,  382,  378,  391,  389,  383,  376,  383,  382,  290,
      289,  295,  298,  299,  186,  300,  306,  311,  309,  312,
      314,  373,  372,  372,  368,  380,  368,  375,  374,  373,

      364,  368,  367,  313,  315,  320,  322,  316,  325,  327,
      374,  329,  331,  334,  362,  353,  363,  360,  359,  347,
      346,  332,  241,  335,  339,  224,  343,  344,  177,  113,
       87,   55,  339,  351,  352,  349,   46,  358,  350,  360,
      362,  363,  364,  470,  383,   22
    } ;

static yyconst flex_int16_t yy_def[247] =
    {   0,
      245,  245,  245,    2,  244,    5,  244,  244,  246,  244,
      246,  246,  246,  244,  244,  244,  246,  246,  246,  246,
      246,   20,   20,   20,   20,   20,   20,   20,   16,   20,
       20,   20,  246,  244,  244,  244,  244,  244,  246,  246,
      244,  246,  244,  246,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  246,  244,  244,  244,  246,
      246,  246,  244,  244,  244,   21,  246,  246,  246,  246,
      246,  246,  246,  246,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  246,  244,  246,  244,  246,  244,
      246,  244,  244,  244,  244,  244,  244,  244,  244,  246,

      246,  246,  246,  246,  246,  246,  246,  246,  246,  246,
      246,  246,   74,  246,  246,  244,  244,  244,  244,  244,
      246,  244,  246,  244,  246,  244,  246,  244,  244,  244,
      244,  244,  244,  244,  244,  246,   74,  246,  246,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  244,
      244,  244,  244,  244,  246,  244,  246,  244,  246,  244,
      246,  244,  244,  244,  244,  244,  244,  244,  244,  246,
      246,  246,  246,  246,  246,  246,  246,  246,  246,  244,
      244,  244,  244,  244,  246,  244,  246,  244,  246,  244,
      246,  244,  244,  244,  244,  244,  244,  244,  244,  246,

      246,  246,  246,  244,  244,  244,  244,  244,  246,  244,
      246,  244,  246,  244,  244,  244,  244,  244,  246,  246,
      246,  244,  244,  244,  244,  244,  244,  246,  244,  244,
      244,  246,   74,  244,  244,  246,  244,  244,  244,  244,
      246,  244,  244,    0,  244,  244
    } ;

static yyconst flex_int16_t yy_nxt[498] =
    {   0,
        8,    8,    8,    8,    8,    8,    8,   10,    8,    8,
       38,   11,   43,   53,   54,   55,   44,   56,   57,   58,
       59,   43,   39,   33,   40,   83,   12,   13,    8,   14,
        8,    8,    8,    8,   15,   16,    8,   16,   17,   18,
       19,   18,   20,   18,   18,   18,   21,   21,   18,   22,
       23,   24,   25,   18,   26,   27,   28,   21,   21,   18,
       29,   33,   34,   41,   30,   41,   35,   99,   67,   53,
       54,   57,   58,   59,   33,   68,   74,   33,   33,   31,
       32,   36,   37,   60,   42,   45,   82,   46,   70,   69,
       33,   33,   33,   72,   47,   48,   73,   49,   86,   50,

       51,   52,   57,   58,   59,   71,   33,   33,  238,   33,
       34,   61,   87,   74,   35,   78,   84,   88,   53,   54,
       33,   41,   89,   72,   62,   63,   64,   65,   85,   75,
       76,   79,  137,   38,  238,   44,   42,   66,   66,   73,
       34,   38,   82,  137,   35,   80,   90,   81,   66,   66,
       77,   91,   33,   80,   86,   81,  106,   43,   33,   36,
       37,   83,   39,  107,   40,   53,   54,   55,  117,   56,
       86,   33,   57,   58,   57,   58,   63,   64,   63,   64,
       53,   54,   55,  101,  117,   43,   41,  237,  208,   83,
      130,  102,  108,   98,   97,   57,   78,  131,   57,   79,

       57,   77,  109,   83,   84,  110,  111,   82,  209,  112,
       53,   54,   55,   80,   88,   81,  116,   82,  114,  118,
       90,  120,   84,  122,  124,  119,  226,   88,  125,  121,
       90,  123,  118,  115,  116,  119,  126,  141,  132,  142,
      156,  120,  122,  226,  127,  133,   53,   54,   55,  150,
      151,  124,  126,  120,  134,  152,  154,  122,  124,  157,
      153,  150,  152,  158,  126,  151,  155,  160,   33,  135,
      173,  154,  153,  101,  156,  159,  158,  160,  184,  161,
      154,  180,  185,   33,  156,  186,  158,  188,  182,  183,
      180,  186,  184,  181,  160,  190,  204,  188,  182,  189,

      190,  184,  186,  181,  187,  204,  183,  191,  210,  206,
      205,  212,  207,  188,  190,  208,  214,  210,  208,  213,
      211,  205,  212,  211,  214,  206,  207,  225,  223,  210,
      224,  212,  223,  227,  225,  222,  214,  227,  222,  224,
      223,  225,  211,  228,  223,  227,  235,  234,   33,  223,
      236,  240,  240,  235,  235,  234,  223,  239,  239,   53,
       54,   55,  240,   33,  243,  243,  243,  233,  233,  232,
      231,  241,  242,  230,   99,  229,  226,  221,  220,  211,
      223,  223,  242,    9,    9,   74,  219,  218,  217,   99,
      216,  215,   99,   99,   99,  203,  202,   74,  101,  201,

      101,  200,   74,   74,   74,  199,  198,  197,  196,  195,
      194,  193,  192,  179,  178,  177,  176,  175,  174,  172,
      101,  101,  171,  170,  101,  169,  168,  167,  166,  165,
      164,  163,  162,  149,  148,  101,  147,  146,  101,  145,
      144,  143,  101,  140,  139,  138,  136,   99,  129,  128,
       99,   99,  113,  105,  104,  103,   74,  100,   74,   99,
       98,   97,   96,   95,   94,   93,   92,  244,   14,    7,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244

    } ;

static yyconst flex_int16_t yy_chk[498] =
    {   0,
        1,    1,    1,    1,    1,    2,    2,    2,    2,    2,
       11,    2,   13,   17,   17,   17,   13,   17,   18,   18,
       18,   37,   11,  246,   11,   37,    2,    2,    3,    3,
        3,    3,    3,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        6,   22,   10,   12,    6,   36,   10,  237,   22,   54,
       54,   19,   19,   19,   22,   23,  232,   23,   24,    6,
        6,   10,   10,   19,   12,   16,   36,   16,   24,   23,
       23,   24,   25,   26,   16,   16,   27,   16,   40,   16,

       16,   16,   20,   20,   20,   25,   26,   28,  231,   27,
       29,   20,   40,   28,   29,   31,   39,   42,   55,   55,
       28,   41,   42,   31,   20,   21,   21,   21,   39,   29,
       29,   32,  101,   35,  230,   32,   31,   21,   21,   32,
       34,   38,   41,  101,   34,   35,   44,   35,   21,   21,
       30,   44,   32,   38,   81,   38,   71,   43,   30,   34,
       34,   43,   30,   71,   30,   56,   56,   56,   81,   56,
       86,   30,   58,   58,   59,   59,   64,   64,   65,   65,
       66,   66,   66,   67,   86,   76,   75,  229,  185,   76,
       96,   67,   72,   76,   75,   78,   78,   96,   79,   79,

       77,   77,   72,   79,   80,   72,   72,   75,  185,   72,
       74,   74,   74,   77,   82,   77,   80,   78,   74,   82,
       83,   85,   84,   87,   89,   83,  226,   88,   89,   85,
       90,   87,   88,   74,   84,   90,   91,  106,   97,  106,
      123,  116,  117,  223,   91,   97,   99,   99,   99,  116,
      117,  118,  119,  120,   99,  118,  121,  122,  124,  123,
      119,  120,  124,  125,  126,  122,  121,  127,  137,   99,
      143,  150,  126,  143,  151,  125,  152,  153,  155,  127,
      154,  150,  155,  137,  156,  157,  158,  159,  152,  153,
      154,  181,  180,  151,  160,  161,  180,  182,  158,  159,

      183,  184,  186,  156,  157,  184,  160,  161,  187,  182,
      181,  189,  183,  188,  190,  204,  191,  205,  208,  189,
      191,  186,  206,  187,  207,  188,  190,  209,  207,  210,
      206,  212,  205,  213,  222,  204,  214,  224,  208,  212,
      214,  225,  209,  213,  210,  227,  228,  224,  233,  222,
      228,  236,  239,  234,  235,  227,  225,  234,  235,  238,
      238,  238,  240,  233,  241,  242,  243,  221,  220,  219,
      218,  236,  239,  217,  216,  215,  211,  203,  202,  241,
      242,  243,  240,  245,  245,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  179,  178,  177,  176,  175,

      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  149,  148,  147,  146,  145,  144,  142,
      141,  140,  139,  138,  136,  135,  134,  133,  132,  131,
      130,  129,  128,  115,  114,  113,  112,  111,  110,  109,
      108,  107,  105,  104,  103,  102,  100,   98,   95,   94,
       93,   92,   73,   70,   69,   68,   62,   61,   60,   52,
       51,   50,   49,   48,   47,   46,   45,    7,    4,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244

    } ;

extern int ann_flex_debug;
int ann_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up anntext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = yy_full_lp; /* restore orig. accepting pos. */ \
(yy_state_ptr) = yy_full_state; /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *anntext;
#line 1 "annessi.lex"
#line 2 "annessi.lex"
// Scanner Case-Insensitive
// compilare con flex -i -8 -Pall nomefile
#include <stdio.h>
#include <string.h>
#include "tag.h"
#include <IttigLogger.h>
#include "xxx.h"
#define __DEBUG__  0

long EndOfLastAllegato=0;
long StartOfLastAllegato=0;
long ann_pos=0;
int firstAnnesso=0;
int LastIDAnnesso=0;

void annIncPos(void){
	ann_pos+=annleng;
}

void salva(void)
{
	LastIDAnnesso++;

	if (firstAnnesso)
	{
		xxxTagOpen(tagerrore,0,0);
		//xxxTagOpen(annessi,StartOfLastAllegato,0);
		firstAnnesso=0;
	}

	xxxTagOpen(annesso,StartOfLastAllegato,0);
	xxxSetID(annesso,LastIDAnnesso,-1);
	xxxTagOpen(testata,StartOfLastAllegato,0);
	xxxTagOpen(denannesso,StartOfLastAllegato,0);
	xxxTagOpen(h_p,StartOfLastAllegato,0);
	xxxTagOpen(titannesso,(ann_pos+annleng),0);
	xxxTagOpen(h_p,(ann_pos+annleng),0);
	xxxTagOpen(preannesso,(ann_pos+annleng),0);
	xxxTagOpen(h_p,(ann_pos+annleng),0);

	xxxTagOpen(tagerrore,(ann_pos+annleng),0);
	loggerDebug("Allegato Trovato");
}
	
void MaybeAllegato(){
	StartOfLastAllegato=ann_pos;
}

void MaybeEndOfAllegato(){
	EndOfLastAllegato=ann_pos;
}




#line 721 "annessi.lex.yy.c"

#define INITIAL 0
#define InCorpoAllegato 1
#define InTestaAllegato 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int annwrap (void );
#else
extern int annwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( anntext, annleng, 1, annout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( annin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( annin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, annin))==0 && ferror(annin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(annin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int annlex (void);

#define YY_DECL int annlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after anntext and annleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( annleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(anntext[annleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 79 "annessi.lex"


#line 880 "annessi.lex.yy.c"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)annalloc(YY_BUF_SIZE + 2  );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! annin )
			annin = stdin;

		if ( ! annout )
			annout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			annensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				ann_create_buffer(annin,YY_BUF_SIZE );
		}

		ann_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of anntext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 245 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 470 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					yy_full_state = (yy_state_ptr);
					yy_full_lp = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 81 "annessi.lex"
{   // NL c'è per forza alla fine???
						
						BEGIN(InTestaAllegato);
						MaybeAllegato();
						annIncPos();
					}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 88 "annessi.lex"
{	//Allegato Numerico|Romano|Latino|Ordinale . Qui anche NL+?
						salva();
						annIncPos();
					}
	YY_BREAK
case 3:
/* rule 3 can match eol */
*yy_cp = (yy_hold_char); /* undo effects of setting up anntext */
(yy_c_buf_p) = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up anntext again */
YY_RULE_SETUP
#line 93 "annessi.lex"
{	//Allegato CARATTERE . Qui anche NL+?
						salva();
						annIncPos();
					}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 98 "annessi.lex"
{ 
						BEGIN(0);
						MaybeEndOfAllegato();
						annIncPos();
					}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 104 "annessi.lex"
{
						MaybeEndOfAllegato();
						annIncPos();
					}
	YY_BREAK
case YY_STATE_EOF(InCorpoAllegato):
#line 109 "annessi.lex"
{

						//if (EndOfLastAllegato!=0)salva();
						BEGIN(0);
					}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 115 "annessi.lex"
{ annIncPos(); BEGIN(0); }
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 116 "annessi.lex"
{ annIncPos(); BEGIN(0); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 118 "annessi.lex"
ECHO;
	YY_BREAK
#line 1064 "annessi.lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(InTestaAllegato):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed annin at a new source and called
			 * annlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = annin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( annwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * anntext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of annlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			annrestart(annin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 245 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    
	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 245 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 244);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up anntext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					annrestart(annin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( annwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve anntext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void annrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        annensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            ann_create_buffer(annin,YY_BUF_SIZE );
	}

	ann_init_buffer(YY_CURRENT_BUFFER,input_file );
	ann_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void ann_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		annpop_buffer_state();
	 *		annpush_buffer_state(new_buffer);
     */
	annensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	ann_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (annwrap()) processing, but the only time this flag
	 * is looked at is after annwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void ann_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	annin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE ann_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) annalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ann_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) annalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in ann_create_buffer()" );

	b->yy_is_our_buffer = 1;

	ann_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with ann_create_buffer()
 * 
 */
    void ann_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		annfree((void *) b->yy_ch_buf  );

	annfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a annrestart() or at EOF.
 */
    static void ann_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	ann_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then ann_init_buffer was _probably_
     * called from annrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void ann_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		ann_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void annpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	annensure_buffer_stack();

	/* This block is copied from ann_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from ann_switch_to_buffer. */
	ann_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void annpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	ann_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		ann_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void annensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)annalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)annrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE ann_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) annalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in ann_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	ann_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to annlex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       ann_scan_bytes() instead.
 */
YY_BUFFER_STATE ann_scan_string (yyconst char * yy_str )
{
    
	return ann_scan_bytes(yy_str,strlen(yy_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to annlex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE ann_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) annalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in ann_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = ann_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in ann_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up anntext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		anntext[annleng] = (yy_hold_char); \
		(yy_c_buf_p) = anntext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		annleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int annget_lineno  (void)
{
        
    return annlineno;
}

/** Get the input stream.
 * 
 */
FILE *annget_in  (void)
{
        return annin;
}

/** Get the output stream.
 * 
 */
FILE *annget_out  (void)
{
        return annout;
}

/** Get the length of the current token.
 * 
 */
int annget_leng  (void)
{
        return annleng;
}

/** Get the current token.
 * 
 */

char *annget_text  (void)
{
        return anntext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void annset_lineno (int  line_number )
{
    
    annlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see ann_switch_to_buffer
 */
void annset_in (FILE *  in_str )
{
        annin = in_str ;
}

void annset_out (FILE *  out_str )
{
        annout = out_str ;
}

int annget_debug  (void)
{
        return ann_flex_debug;
}

void annset_debug (int  bdebug )
{
        ann_flex_debug = bdebug ;
}

/* annlex_destroy is for both reentrant and non-reentrant scanners. */
int annlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		ann_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		annpop_buffer_state();
	}

	/* Destroy the stack itself. */
	annfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    annfree ( (yy_state_buf) );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *annalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *annrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void annfree (void * ptr )
{
	free( (char *) ptr );	/* see annrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef yy_set_bol
#undef yy_new_buffer
#undef yy_set_interactive
#undef yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif
#line 118 "annessi.lex"



int annwrap()
{
	return 1;
}

//Restituisce il numero di annessi trovati
int  _annessiLexStart(char *testo)
{
	BEGIN(0);
	yy_init = 1;
	ann_pos=0;
	LastIDAnnesso=0;
	EndOfLastAllegato=0;
	StartOfLastAllegato=0;
	firstAnnesso=1;
	ann_scan_string(testo);
	annlex();
	
	return LastIDAnnesso;
}

//void ann_inizio_scansione(FILE* file_desc)
//{
//	BEGIN(0);
//	yy_init = 1;
//	ann_pos=0;
//	EndOfLastAllegato=0;
//	StartOfLastAllegato=0;
//	annrestart(file_desc);
//	annin = file_desc;
//	annout=fopen("ppp.txt","w");
//	annlex();
//}


