#line 2 "prehtml.lex.yy.c"

#line 4 "prehtml.lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 31
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined __STDC_VERSION__ && __STDC_VERSION__ >= 199901L
#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE prehtmlrestart(prehtmlin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int prehtmlleng;

extern FILE *prehtmlin, *prehtmlout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prehtmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up prehtmltext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via prehtmlrestart()), so that the user can continue scanning by
	 * just pointing prehtmlin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when prehtmltext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int prehtmlleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow prehtmlwrap()'s to do buffer switches
 * instead of setting up a fresh prehtmlin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void prehtmlrestart (FILE *input_file  );
void prehtml_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE prehtml_create_buffer (FILE *file,int size  );
void prehtml_delete_buffer (YY_BUFFER_STATE b  );
void prehtml_flush_buffer (YY_BUFFER_STATE b  );
void prehtmlpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void prehtmlpop_buffer_state (void );

static void prehtmlensure_buffer_stack (void );
static void prehtml_load_buffer_state (void );
static void prehtml_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER prehtml_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE prehtml_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE prehtml_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE prehtml_scan_bytes (yyconst char *bytes,int len  );

void *prehtmlalloc (yy_size_t  );
void *prehtmlrealloc (void *,yy_size_t  );
void prehtmlfree (void *  );

#define yy_new_buffer prehtml_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        prehtmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prehtml_create_buffer(prehtmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        prehtmlensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prehtml_create_buffer(prehtmlin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *prehtmlin = (FILE *) 0, *prehtmlout = (FILE *) 0;

typedef int yy_state_type;

extern int prehtmllineno;

int prehtmllineno = 1;

extern char *prehtmltext;
#define yytext_ptr prehtmltext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up prehtmltext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	prehtmlleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 42
#define YY_END_OF_BUFFER 43
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[272] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       20,   20,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   43,   41,   13,    5,   19,   41,
       32,   32,   28,   32,   32,   42,    7,    7,    7,   20,
       21,   17,   18,   25,   25,   25,   37,   37,   36,   37,
       10,   10,   10,    0,    0,    0,    0,    0,    0,   22,
        6,    0,    0,    0,    0,    0,    0,   16,    0,    0,
       23,   32,   32,   32,    7,    8,   20,   25,    0,   37,
       37,    0,   10,    0,    3,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   34,   27,    0,    0,

        0,    0,   32,   32,   20,    0,    0,    0,   37,   11,
        4,    0,    0,    9,    0,    0,    0,    0,   15,   16,
        0,    0,    0,    0,    0,    0,   33,   32,   32,   20,
        0,    0,    0,    0,   37,    0,    0,   38,   39,    0,
       40,   24,   12,    0,    0,   32,    0,   20,    0,    0,
        0,    0,   37,    2,    1,   14,    0,    0,    0,   29,
       30,   20,    0,    0,    0,    0,    0,   31,   29,   30,
       20,   26,    0,    0,   35,   31,   20,   35,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,

       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    1,    6,    1,    1,
        1,    1,    1,    1,    7,    1,    8,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,   10,   11,
       12,   13,   14,    1,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   21,   21,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   21,   21,   35,   21,
        1,    1,    1,    1,    1,    1,   15,   16,   17,   18,

       19,   20,   21,   22,   23,   21,   21,   24,   25,   26,
       27,   28,   29,   30,   31,   32,   33,   34,   21,   21,
       35,   21,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[36] =
    {   0,
        1,    1,    1,    2,    3,    1,    1,    1,    4,    1,
        1,    1,    5,    1,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[387] =
    {   0,
        0,    1,   14,    0,    0,    0,    0,    0,   49,   63,
      585,  579,    0,    0,    0,    0,  573,  567,   77,   91,
      105,  139,  173,  187,  574,  912,  912,   95,  199,  555,
      912,    0,  912,  530,  521,  912,  912,    0,  537,    0,
      912,  912,  912,  912,    0,  536,  912,    0,  912,  523,
      912,  525,    0,  517,    0,  115,  122,  513,  102,  912,
      912,  484,  485,  475,  477,  467,  460,  448,  105,  448,
      912,    0,  451,  432,    0,  912,    0,    0,  134,    0,
      430,  435,    0,  124,  912,  198,  201,  435,  413,  406,
      394,  394,  399,  372,  370,  379,  912,  912,  369,  352,

      341,  357,  334,  339,    0,  325,  327,  106,  307,  912,
      912,  154,  199,  912,  325,  322,  310,  304,  912,  912,
      286,  290,  292,  279,  272,  280,  912,  258,  277,    0,
      207,  221,  205,  189,  203,  152,  153,  912,  912,  205,
      912,  912,  912,  188,  195,  200,    0,    0,  180,  178,
      148,  146,  157,  912,  912,  912,  136,  157,  163,  156,
      144,    0,  123,  100,   95,  216,   77,  229,  912,  912,
        0,  912,   40,   49,  230,  912,    0,  912,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  912,
      912,  239,  245,  251,  257,  263,  269,  275,  281,  285,
      288,  291,  297,  300,  303,  306,  312,  318,  324,  330,
      335,  341,  347,  353,  359,  365,  371,  377,  383,  389,

      395,  401,  407,  413,  419,  425,  431,  437,  443,  449,
      455,  461,  467,  473,  479,  485,  491,  497,  503,  509,
      515,  521,  527,  533,  539,  545,  551,  557,  563,  569,
      575,  581,  587,  593,  599,  605,  611,  617,  623,  629,
      635,  641,  647,  653,  659,  665,  671,  677,  683,  689,
      695,  701,  707,  713,  719,  725,  731,  737,  743,  749,
      755,  761,  767,  773,  779,  785,  791,  797,  803,  809,
      815,  821,  827,  833,  839,  845,  851,  857,  863,  869,
      875,  881,  887,  893,  899,  905
    } ;

static yyconst flex_int16_t yy_def[387] =
    {   0,
      272,  272,  271,    3,  273,  273,  273,  273,  274,  274,
      275,  275,  273,  273,  273,  273,  276,  276,  277,  277,
      278,  278,  279,  279,  271,  271,  271,  280,  271,  271,
      271,  281,  271,  281,  281,  271,  271,  282,  271,  283,
      271,  271,  271,  271,  284,  271,  271,  285,  271,  285,
      271,  271,  286,  271,  280,  280,  280,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  281,  281,  281,  282,  271,  287,  284,  271,  285,
      285,  271,  286,  271,  271,  280,  280,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  288,  281,  281,  289,  271,  271,  271,  285,  271,
      271,  280,  280,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  288,  271,  281,  281,  290,
      271,  271,  271,  271,  285,  280,  280,  271,  271,  271,
      271,  271,  271,  271,  271,  281,  291,  292,  271,  271,
      271,  271,  285,  271,  271,  271,  271,  271,  291,  271,
      271,  293,  271,  271,  271,  271,  271,  271,  271,  271,
      294,  271,  271,  271,  271,  271,  295,  271,  296,  297,
      298,  299,  300,  301,  302,  303,  304,  305,  306,  307,
      308,  309,  310,  311,  312,  313,  314,  315,  316,  317,

      318,  319,  320,  321,  322,  323,  324,  325,  326,  327,
      328,  329,  330,  331,  332,  333,  334,  335,  336,  337,
      338,  339,  340,  341,  342,  343,  344,  345,  346,  347,
      348,  349,  350,  351,  352,  353,  354,  355,  356,  357,
      358,  359,  360,  361,  362,  363,  364,  365,  366,  367,
      368,  369,  370,  371,  372,  373,  374,  375,  376,  377,
      378,  379,  380,  381,  382,  383,  384,  385,  386,  271,
        0,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,

      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271
    } ;

static yyconst flex_int16_t yy_nxt[948] =
    {   0,
      271,   27,   27,  159,  271,   28,   28,  271,  160,   85,
       29,   29,   30,   30,   31,   31,   31,   31,   31,   31,
       31,   31,   32,   31,   31,   31,   33,   31,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   34,   35,   32,   32,   32,   37,
       37,   37,   37,   37,   37,   37,   37,  175,   37,   37,
       37,   37,   39,   37,   37,   37,   37,   37,   37,   37,
       37,  163,   37,   37,   37,   37,   39,   44,   44,   44,
       44,   44,   44,   44,   44,  168,   44,   46,   44,   44,
       44,   44,   44,   44,   44,   44,   44,   44,   44,   54,

       44,   46,   44,   44,   44,   47,   47,   47,   47,   47,
       47,   47,   47,  163,   47,   47,   47,   49,   47,  271,
       56,  100,  133,   57,   85,   89,  271,  173,   90,   91,
       86,   85,   84,  111,   92,  172,  101,  134,   50,   47,
       47,   47,   47,   47,   47,   47,   47,  170,   47,   47,
       47,   49,   47,  106,   87,  107,  271,  271,  271,  169,
      167,  154,  155,   85,  108,  168,  271,  142,  166,  165,
      164,  160,   50,   51,   51,   51,   51,   51,   51,   52,
       51,  136,   51,   51,   51,   51,   51,   51,   51,   51,
       51,   51,   51,   52,   51,  163,   51,   51,   51,   51,

       51,   58,  271,  271,  163,  271,   59,   85,   85,   60,
       85,  158,   61,  142,   62,  157,   63,  156,   64,  174,
       65,  153,   66,  152,  175,   67,   68,  113,  112,   69,
      137,   70,  176,  178,  151,  150,  149,  168,  175,   26,
       26,   26,   26,   26,   26,   36,   36,   36,   36,   36,
       36,   38,   38,   38,   38,   38,   38,   40,   40,   40,
       40,   40,   40,   42,   42,   42,   42,   42,   42,   45,
       45,   45,   45,   45,   45,   48,   48,   48,   48,   48,
       48,   53,   53,   53,   53,   53,   53,   55,  147,  146,
       55,   72,  127,   72,   75,  145,   75,   77,   77,   77,

       77,  144,   77,   78,  143,   78,   80,  142,   80,   83,
      142,   83,  105,  105,  105,  105,  141,  105,  126,  126,
      126,  126,  126,  126,  130,  130,  130,  130,  140,  130,
      148,  148,  148,  148,  139,  148,  161,  138,  161,  135,
      161,  162,  162,  162,  162,  132,  162,  171,  171,  171,
      171,  131,  171,  177,  177,  177,  177,  129,  177,  179,
      179,  179,  179,  128,  179,  180,  180,  180,  180,  127,
      180,  181,  181,  181,  181,  125,  181,  182,  182,  182,
      182,  124,  182,  183,  183,  183,  183,  123,  183,  184,
      184,  184,  184,  122,  184,  185,  185,  185,  185,  121,

      185,  186,  186,  186,  186,  120,  186,  187,  187,  187,
      187,  119,  187,  188,  188,  188,  188,  118,  188,  189,
      189,  189,  189,  117,  189,  190,  190,  190,  190,  116,
      190,  191,  191,  191,  191,  115,  191,  192,  192,  192,
      192,  114,  192,  193,  193,  193,  193,  110,  193,  194,
      194,  194,  194,  109,  194,  195,  195,  195,  195,  104,
      195,  196,  196,  196,  196,  103,  196,  197,  197,  197,
      197,  102,  197,  198,  198,  198,  198,   99,  198,  199,
      199,  199,  199,   98,  199,  200,  200,  200,  200,   97,
      200,  201,  201,  201,  201,   96,  201,  202,  202,  202,

      202,   95,  202,  203,  203,  203,  203,   94,  203,  204,
      204,  204,  204,   93,  204,  205,  205,  205,  205,   88,
      205,  206,  206,  206,  206,   84,  206,  207,  207,  207,
      207,   82,  207,  208,  208,  208,  208,   81,  208,  209,
      209,  209,  209,   79,  209,  210,  210,  210,  210,   76,
      210,  211,  211,  211,  211,   74,  211,  212,  212,  212,
      212,   73,  212,  213,  213,  213,  213,   71,  213,  214,
      214,  214,  214,  271,  214,  215,  215,  215,  215,   43,
      215,  216,  216,  216,  216,   43,  216,  217,  217,  217,
      217,   41,  217,  218,  218,  218,  218,   41,  218,  219,

      219,  219,  219,  271,  219,  220,  220,  220,  220,  271,
      220,  221,  221,  221,  221,  271,  221,  222,  222,  222,
      222,  271,  222,  223,  223,  223,  223,  271,  223,  224,
      224,  224,  224,  271,  224,  225,  225,  225,  225,  271,
      225,  226,  226,  226,  226,  271,  226,  227,  227,  227,
      227,  271,  227,  228,  228,  228,  228,  271,  228,  229,
      229,  229,  229,  271,  229,  230,  230,  230,  230,  271,
      230,  231,  231,  231,  231,  271,  231,  232,  232,  232,
      232,  271,  232,  233,  233,  233,  233,  271,  233,  234,
      234,  234,  234,  271,  234,  235,  235,  235,  235,  271,

      235,  236,  236,  236,  236,  271,  236,  237,  237,  237,
      237,  271,  237,  238,  238,  238,  238,  271,  238,  239,
      239,  239,  239,  271,  239,  240,  240,  240,  240,  271,
      240,  241,  241,  241,  241,  271,  241,  242,  242,  242,
      242,  271,  242,  243,  243,  243,  243,  271,  243,  244,
      244,  244,  244,  271,  244,  245,  245,  245,  245,  271,
      245,  246,  246,  246,  246,  271,  246,  247,  247,  247,
      247,  271,  247,  248,  248,  248,  248,  271,  248,  249,
      249,  249,  249,  271,  249,  250,  250,  250,  250,  271,
      250,  251,  251,  251,  251,  271,  251,  252,  252,  252,

      252,  271,  252,  253,  253,  253,  253,  271,  253,  254,
      254,  254,  254,  271,  254,  255,  255,  255,  255,  271,
      255,  256,  256,  256,  256,  271,  256,  257,  257,  257,
      257,  271,  257,  258,  258,  258,  258,  271,  258,  259,
      259,  259,  259,  271,  259,  260,  260,  260,  260,  271,
      260,  261,  261,  261,  261,  271,  261,  262,  262,  262,
      262,  271,  262,  263,  263,  263,  263,  271,  263,  264,
      264,  264,  264,  271,  264,  265,  265,  265,  265,  271,
      265,  266,  266,  266,  266,  271,  266,  267,  267,  267,
      267,  271,  267,  268,  268,  268,  268,  271,  268,  269,

      269,  269,  269,  271,  269,  270,  270,  270,  270,  271,
      270,   25,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271
    } ;

static yyconst flex_int16_t yy_chk[948] =
    {   0,
        0,    1,    2,  147,   55,    1,    2,    0,  147,   55,
        1,    2,    1,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    9,
        9,    9,    9,    9,    9,    9,    9,  174,    9,    9,
        9,    9,    9,   10,   10,   10,   10,   10,   10,   10,
       10,  173,   10,   10,   10,   10,   10,   19,   19,   19,
       19,   19,   19,   19,   19,  167,   19,   19,   19,   19,
       19,   20,   20,   20,   20,   20,   20,   20,   20,   28,

       20,   20,   20,   20,   20,   21,   21,   21,   21,   21,
       21,   21,   21,  165,   21,   21,   21,   21,   21,   56,
       28,   69,  108,   28,   56,   59,   57,  164,   59,   59,
       56,   57,   84,   84,   59,  163,   69,  108,   21,   22,
       22,   22,   22,   22,   22,   22,   22,  161,   22,   22,
       22,   22,   22,   79,   57,   79,  136,  137,  112,  160,
      158,  136,  137,  112,   79,  158,  159,  157,  153,  152,
      151,  159,   22,   23,   23,   23,   23,   23,   23,   23,
       23,  112,   23,   23,   23,   23,   23,   24,   24,   24,
       24,   24,   24,   24,   24,  150,   24,   24,   24,   24,

       24,   29,   86,  113,  149,   87,   29,   86,  113,   29,
       87,  146,   29,  145,   29,  144,   29,  140,   29,  166,
       29,  135,   29,  134,  166,   29,   29,   87,   86,   29,
      113,   29,  168,  175,  133,  132,  131,  168,  175,  272,
      272,  272,  272,  272,  272,  273,  273,  273,  273,  273,
      273,  274,  274,  274,  274,  274,  274,  275,  275,  275,
      275,  275,  275,  276,  276,  276,  276,  276,  276,  277,
      277,  277,  277,  277,  277,  278,  278,  278,  278,  278,
      278,  279,  279,  279,  279,  279,  279,  280,  129,  128,
      280,  281,  126,  281,  282,  125,  282,  283,  283,  283,

      283,  124,  283,  284,  123,  284,  285,  122,  285,  286,
      121,  286,  287,  287,  287,  287,  118,  287,  288,  288,
      288,  288,  288,  288,  289,  289,  289,  289,  117,  289,
      290,  290,  290,  290,  116,  290,  291,  115,  291,  109,
      291,  292,  292,  292,  292,  107,  292,  293,  293,  293,
      293,  106,  293,  294,  294,  294,  294,  104,  294,  295,
      295,  295,  295,  103,  295,  296,  296,  296,  296,  102,
      296,  297,  297,  297,  297,  101,  297,  298,  298,  298,
      298,  100,  298,  299,  299,  299,  299,   99,  299,  300,
      300,  300,  300,   96,  300,  301,  301,  301,  301,   95,

      301,  302,  302,  302,  302,   94,  302,  303,  303,  303,
      303,   93,  303,  304,  304,  304,  304,   92,  304,  305,
      305,  305,  305,   91,  305,  306,  306,  306,  306,   90,
      306,  307,  307,  307,  307,   89,  307,  308,  308,  308,
      308,   88,  308,  309,  309,  309,  309,   82,  309,  310,
      310,  310,  310,   81,  310,  311,  311,  311,  311,   74,
      311,  312,  312,  312,  312,   73,  312,  313,  313,  313,
      313,   70,  313,  314,  314,  314,  314,   68,  314,  315,
      315,  315,  315,   67,  315,  316,  316,  316,  316,   66,
      316,  317,  317,  317,  317,   65,  317,  318,  318,  318,

      318,   64,  318,  319,  319,  319,  319,   63,  319,  320,
      320,  320,  320,   62,  320,  321,  321,  321,  321,   58,
      321,  322,  322,  322,  322,   54,  322,  323,  323,  323,
      323,   52,  323,  324,  324,  324,  324,   50,  324,  325,
      325,  325,  325,   46,  325,  326,  326,  326,  326,   39,
      326,  327,  327,  327,  327,   35,  327,  328,  328,  328,
      328,   34,  328,  329,  329,  329,  329,   30,  329,  330,
      330,  330,  330,   25,  330,  331,  331,  331,  331,   18,
      331,  332,  332,  332,  332,   17,  332,  333,  333,  333,
      333,   12,  333,  334,  334,  334,  334,   11,  334,  335,

      335,  335,  335,    0,  335,  336,  336,  336,  336,    0,
      336,  337,  337,  337,  337,    0,  337,  338,  338,  338,
      338,    0,  338,  339,  339,  339,  339,    0,  339,  340,
      340,  340,  340,    0,  340,  341,  341,  341,  341,    0,
      341,  342,  342,  342,  342,    0,  342,  343,  343,  343,
      343,    0,  343,  344,  344,  344,  344,    0,  344,  345,
      345,  345,  345,    0,  345,  346,  346,  346,  346,    0,
      346,  347,  347,  347,  347,    0,  347,  348,  348,  348,
      348,    0,  348,  349,  349,  349,  349,    0,  349,  350,
      350,  350,  350,    0,  350,  351,  351,  351,  351,    0,

      351,  352,  352,  352,  352,    0,  352,  353,  353,  353,
      353,    0,  353,  354,  354,  354,  354,    0,  354,  355,
      355,  355,  355,    0,  355,  356,  356,  356,  356,    0,
      356,  357,  357,  357,  357,    0,  357,  358,  358,  358,
      358,    0,  358,  359,  359,  359,  359,    0,  359,  360,
      360,  360,  360,    0,  360,  361,  361,  361,  361,    0,
      361,  362,  362,  362,  362,    0,  362,  363,  363,  363,
      363,    0,  363,  364,  364,  364,  364,    0,  364,  365,
      365,  365,  365,    0,  365,  366,  366,  366,  366,    0,
      366,  367,  367,  367,  367,    0,  367,  368,  368,  368,

      368,    0,  368,  369,  369,  369,  369,    0,  369,  370,
      370,  370,  370,    0,  370,  371,  371,  371,  371,    0,
      371,  372,  372,  372,  372,    0,  372,  373,  373,  373,
      373,    0,  373,  374,  374,  374,  374,    0,  374,  375,
      375,  375,  375,    0,  375,  376,  376,  376,  376,    0,
      376,  377,  377,  377,  377,    0,  377,  378,  378,  378,
      378,    0,  378,  379,  379,  379,  379,    0,  379,  380,
      380,  380,  380,    0,  380,  381,  381,  381,  381,    0,
      381,  382,  382,  382,  382,    0,  382,  383,  383,  383,
      383,    0,  383,  384,  384,  384,  384,    0,  384,  385,

      385,  385,  385,    0,  385,  386,  386,  386,  386,    0,
      386,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  271,  271,  271,  271
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int prehtml_flex_debug;
int prehtml_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *prehtmltext;
#line 1 "prehtml.lex"
#line 2 "prehtml.lex"
#include <stdio.h>
#include <string.h>
#include <IttigUtil.h>
#include <IttigLogger.h>

#include "config.h"
#include "prehtml.h"
#include "pre.h"

int Lista[20];
int Tipo[20];
int ii,jj;
int flagpre = 0;
static int numStart;
char ExtractChar;

//char *numLI;
char *cifre = NULL;
char *Uita = NULL;

int prehtmlwrap() 
{
	return 1;
}

void azzera(void)
{

	for (ii=0; ii<20; ii++)
	{
		Lista[ii] = 0;
		Tipo[ii] = -1;
	}
	ii = 0;
	jj = 0;
}


//\<pre>							flagpre=1;

//{NL}							{
//								if (flagpre==0) prehtmlAppendChars(1,' ');
//								if (flagpre==1)	prehtmlAppendChars(1,'\n');}
								
//\<\/pre>						flagpre=0;




#line 812 "prehtml.lex.yy.c"

#define INITIAL 0
#define InTagLista 1
#define ListaTipo 2
#define ListaStart 3
#define InPI 4
#define InTag 5
#define InTagListaNonOrd 6
#define InTagBA 7
#define InTagDiv 8
#define InTagDel 9
#define InTagElementList 10
#define InComment 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int prehtmlwrap (void );
#else
extern int prehtmlwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = 0;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
    static int yy_top_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( prehtmltext, prehtmlleng, 1, prehtmlout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( prehtmlin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( prehtmlin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, prehtmlin))==0 && ferror(prehtmlin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(prehtmlin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int prehtmllex (void);

#define YY_DECL int prehtmllex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after prehtmltext and prehtmlleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 73 "prehtml.lex"


#line 987 "prehtml.lex.yy.c"

	if ( (yy_init) )
		{
		(yy_init) = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! prehtmlin )
			prehtmlin = stdin;

		if ( ! prehtmlout )
			prehtmlout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			prehtmlensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				prehtml_create_buffer(prehtmlin,YY_BUF_SIZE );
		}

		prehtml_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of prehtmltext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 272 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 912 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 75 "prehtml.lex"
prehtmlAppendChars(1, '"');		// convertite virgolette
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 76 "prehtml.lex"
prehtmlAppendChars(1, ' ');		// convertito spazio non divisibile
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));	// lasciate entità simboliche
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));	// lasciate entità numeriche
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 81 "prehtml.lex"
norAppendString("&#38;");		// & che non delimita un'entità
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 84 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(InPI);}
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 88 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 90 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(0);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 94 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(InComment);}
	YY_BREAK
case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 98 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "prehtml.lex"
{
							prehtmlAppendString(strdup(prehtmltext));
							BEGIN(0);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 104 "prehtml.lex"
{	
							flagpre=1;}
	YY_BREAK
case 13:
/* rule 13 can match eol */
YY_RULE_SETUP
#line 107 "prehtml.lex"
{
								if (flagpre==0) prehtmlAppendChars(1,' ');
								if (flagpre==1)	prehtmlAppendChars(1,'\n');}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 111 "prehtml.lex"
{
								flagpre=0;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 115 "prehtml.lex"
{
								prehtmlAppendChars(1, '\n'); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "prehtml.lex"
{		
								prehtmlAppendChars(2, '\n');
								BEGIN(InTagDiv);}
	YY_BREAK
case 17:
/* rule 17 can match eol */
YY_RULE_SETUP
#line 121 "prehtml.lex"

	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "prehtml.lex"
BEGIN(0);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 124 "prehtml.lex"
{
								BEGIN(InTag);}
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 126 "prehtml.lex"

	YY_BREAK
case 21:
YY_RULE_SETUP
#line 127 "prehtml.lex"
{
								BEGIN(0);}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 131 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 133 "prehtml.lex"
{
								jj++;							
								BEGIN(InTagDel);}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 136 "prehtml.lex"

	YY_BREAK
case 26:
YY_RULE_SETUP
#line 137 "prehtml.lex"
{
								jj--;
								if (jj==0)
									BEGIN(0);}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 142 "prehtml.lex"
{
								ii++;BEGIN(InTagLista);}	
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 144 "prehtml.lex"
{
								if (Tipo[ii]==-1) Tipo[ii]=1; //Se non c'è il tipo di defaut è numerica
								BEGIN(0);}					
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 148 "prehtml.lex"
{
								Tipo[ii]=1; //lista numerica
								}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 151 "prehtml.lex"
{
								Tipo[ii]=0; //lista alfabetica
								}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 154 "prehtml.lex"
{
								cifre=utilIsolaNum(prehtmltext); 
								numStart = atoi(cifre);
								Lista[ii]=(numStart-1);
								}
	YY_BREAK
case 32:
/* rule 32 can match eol */
YY_RULE_SETUP
#line 160 "prehtml.lex"

	YY_BREAK
case 33:
/* rule 33 can match eol */
YY_RULE_SETUP
#line 162 "prehtml.lex"
ii++; Tipo[ii]=2; //lista puntata
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 168 "prehtml.lex"
Lista[ii]++;BEGIN(InTagElementList);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 170 "prehtml.lex"
{
											cifre=utilIsolaNum(prehtmltext); 
											numStart = atoi(cifre);
											Lista[ii]=(numStart-1);
											}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 176 "prehtml.lex"
{
						
						prehtmlAppendChars(2,'\n');
						if (Tipo[ii]==1)
							{
							
							Uita=utilItoa(Lista[ii]);					
							prehtmlAppendString(Uita);//visualizza il numero
							prehtmlAppendChars(1,')');
							prehtmlAppendChars(1,' ');
							}
						if (Tipo[ii]==0)
							{
							ExtractChar = prehtmlExtractChar(Lista[ii]);
							if (Lista[ii]<27)
								prehtmlAppendChars(1,ExtractChar);
							else if (Lista[ii]<677)
								prehtmlAppendChars(2,ExtractChar);
							else
								prehtmlAppendChars(3,ExtractChar);
							prehtmlAppendChars(1,')');
							prehtmlAppendChars(1,' ');
							}
						if (Tipo[ii]==2)
							{
							prehtmlAppendChars(1,'-');
							prehtmlAppendChars(1,' ');
							}

						BEGIN(0);
						}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 208 "prehtml.lex"

	YY_BREAK
case 38:
YY_RULE_SETUP
#line 215 "prehtml.lex"

	YY_BREAK
case 39:
YY_RULE_SETUP
#line 216 "prehtml.lex"
{
								prehtmlAppendChars(2,'\n');
								Lista[ii]=0;
								ii--; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 220 "prehtml.lex"
{
								prehtmlAppendChars(2,'\n');
								Lista[ii]=0;
								ii--; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 225 "prehtml.lex"
prehtmlAppendString(strdup(prehtmltext));
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 228 "prehtml.lex"
ECHO;
	YY_BREAK
#line 1362 "prehtml.lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(InTagLista):
case YY_STATE_EOF(ListaTipo):
case YY_STATE_EOF(ListaStart):
case YY_STATE_EOF(InPI):
case YY_STATE_EOF(InTag):
case YY_STATE_EOF(InTagListaNonOrd):
case YY_STATE_EOF(InTagBA):
case YY_STATE_EOF(InTagDiv):
case YY_STATE_EOF(InTagDel):
case YY_STATE_EOF(InTagElementList):
case YY_STATE_EOF(InComment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed prehtmlin at a new source and called
			 * prehtmllex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = prehtmlin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( prehtmlwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * prehtmltext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of prehtmllex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					prehtmlrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			prehtmlrestart(prehtmlin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 272 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 272 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 271);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up prehtmltext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					prehtmlrestart(prehtmlin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( prehtmlwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve prehtmltext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void prehtmlrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        prehtmlensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            prehtml_create_buffer(prehtmlin,YY_BUF_SIZE );
	}

	prehtml_init_buffer(YY_CURRENT_BUFFER,input_file );
	prehtml_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void prehtml_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		prehtmlpop_buffer_state();
	 *		prehtmlpush_buffer_state(new_buffer);
     */
	prehtmlensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	prehtml_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (prehtmlwrap()) processing, but the only time this flag
	 * is looked at is after prehtmlwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void prehtml_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	prehtmlin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE prehtml_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) prehtmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prehtml_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) prehtmlalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in prehtml_create_buffer()" );

	b->yy_is_our_buffer = 1;

	prehtml_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with prehtml_create_buffer()
 * 
 */
    void prehtml_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		prehtmlfree((void *) b->yy_ch_buf  );

	prehtmlfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a prehtmlrestart() or at EOF.
 */
    static void prehtml_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	prehtml_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then prehtml_init_buffer was _probably_
     * called from prehtmlrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void prehtml_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		prehtml_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void prehtmlpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	prehtmlensure_buffer_stack();

	/* This block is copied from prehtml_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from prehtml_switch_to_buffer. */
	prehtml_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void prehtmlpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	prehtml_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		prehtml_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void prehtmlensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)prehtmlalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)prehtmlrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE prehtml_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) prehtmlalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prehtml_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	prehtml_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to prehtmllex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       prehtml_scan_bytes() instead.
 */
YY_BUFFER_STATE prehtml_scan_string (yyconst char * yy_str )
{
    
	return prehtml_scan_bytes(yy_str,strlen(yy_str) );
}

/** Setup the input buffer state to scan the given bytes. The next call to prehtmllex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE prehtml_scan_bytes  (yyconst char * bytes, int  len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) prehtmlalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in prehtml_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = prehtml_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in prehtml_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) prehtmlalloc(new_size  );

		else
			(yy_start_stack) = (int *) prehtmlrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prehtmltext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		prehtmltext[prehtmlleng] = (yy_hold_char); \
		(yy_c_buf_p) = prehtmltext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		prehtmlleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int prehtmlget_lineno  (void)
{
        
    return prehtmllineno;
}

/** Get the input stream.
 * 
 */
FILE *prehtmlget_in  (void)
{
        return prehtmlin;
}

/** Get the output stream.
 * 
 */
FILE *prehtmlget_out  (void)
{
        return prehtmlout;
}

/** Get the length of the current token.
 * 
 */
int prehtmlget_leng  (void)
{
        return prehtmlleng;
}

/** Get the current token.
 * 
 */

char *prehtmlget_text  (void)
{
        return prehtmltext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void prehtmlset_lineno (int  line_number )
{
    
    prehtmllineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see prehtml_switch_to_buffer
 */
void prehtmlset_in (FILE *  in_str )
{
        prehtmlin = in_str ;
}

void prehtmlset_out (FILE *  out_str )
{
        prehtmlout = out_str ;
}

int prehtmlget_debug  (void)
{
        return prehtml_flex_debug;
}

void prehtmlset_debug (int  bdebug )
{
        prehtml_flex_debug = bdebug ;
}

/* prehtmllex_destroy is for both reentrant and non-reentrant scanners. */
int prehtmllex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		prehtml_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		prehtmlpop_buffer_state();
	}

	/* Destroy the stack itself. */
	prehtmlfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        prehtmlfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
    	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
    	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *prehtmlalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *prehtmlrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void prehtmlfree (void * ptr )
{
	free( (char *) ptr );	/* see prehtmlrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#undef YY_NEW_FILE
#undef YY_FLUSH_BUFFER
#undef yy_set_bol
#undef yy_new_buffer
#undef yy_set_interactive
#undef yytext_ptr
#undef YY_DO_BEFORE_ACTION

#ifdef YY_DECL_IS_OURS
#undef YY_DECL_IS_OURS
#undef YY_DECL
#endif
#line 228 "prehtml.lex"


